[theme]
base = "light"
primaryColor = "#05275F"
backgroundColor = "#F2F4F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#12264A"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
